story1/urls.py
from django.urls import path, include
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.main, name="index"),
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.kuliah, name="index"),
    path('<int:id>/', views.detail_kuliah, name='detail_kuliah'),
    path('<int:id>/delete/', views.delete_kuliah, name='delete_kuliah'),
    path('edit/', views.editor, name="editor"),
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.kegiatan, name="index"),
    path('<int:id>/register/', views.register, name='register'),
    path('peserta/<int:id>/delete/', views.hapus_peserta, name='hapus_peserta'),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.index, name="index"),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.index, name="index"),
    # path('create_book/', views.create_book, name='create_book'),
    path('search/', views.get_book, name='create_book'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
]

story1/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

story1/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def main(request):
	return render(request, 'story1.html')

story7/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

# Create your views here.

def index(request):
	return render(request, 'story7.html')

story8/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
import requests

# Create your views here.

def index(request):
	return render(request, 'story8.html')

def get_book(request):
	if request.GET:
		url = f"https://www.googleapis.com/books/v1/volumes?q={request.GET['q']}&maxResults=12"
		r = requests.get(url);
		return JsonResponse(r.json())

	return JsonResponse({'data':None})

# def create_book(request) :
#     if(request.is_ajax()) :
#         Books.objects.create(title=request.POST['title'], author=request.POST['author'], publisher=request.POST['publisher'], publishedDate=request.POST['publishedDate'], likes=0)

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth

# Create your views here.
def index(request) :
	msg = request.session.get('msg', None)
	try:
		del request.session['msg']
	except:
		pass

	context = {
		'msg' : msg,
	}
	return render(request, 'story9.html', context)

def register(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
       	password = request.POST['password']

       	hasil = "Registration Complete"
       	if User.objects.filter(username=email).exists() :
       		hasil = "Email already exist, try login instead"
       	else :
       		user = User.objects.create_user(username=email, email=email, password=password, first_name=name)
       		user.save()
        	hasil = "Registration Complete, now you may Login"

        request.session['msg'] = hasil
        

    return redirect('/story9/')

def login(request):
    if request.method == 'POST':
        username = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        hasil = ''
        if user is not None:
            auth.login(request, user)
            request.session.set_expiry(300) # auto logout dalam 5 menit
            hasil = 'Login success'
        else :
        	hasil = "Wrong Username or Password"

        request.session['msg'] = hasil
        
    
    return redirect('/story9/')

def logout(request):
    auth.logout(request)
    return redirect("../")

templates/base.html
{% load static %}
{% load google_analytics_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS Layout -->
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- Tambahan CSS -->
    {% block css %}

    {% endblock css %}

    <title>{% block title %}{% endblock title %}</title>
</head>
<body class="d-flex flex-column min-vh-100" style="position: relative;">
<header class="header">

    <div style="display:none">
        <img src="{% google_analytics %}" width="0" height="0" />
    </div>
    <nav class="navbar navbar-expand-lg navbar-light shadow-sm py-3">
        <div class="container">
            <a class="navbar-brand" href="/">Widyanto</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link scroll-link" href="/#aboutme">About me</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link scroll-link" href="/gallery">More</a>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Stories
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item nav-link" href="{% url 'story1:index' %}">Story 1</a>
                        <a class="dropdown-item nav-link" href="{% url 'story5:index' %}">Story 5</a>
                        <a class="dropdown-item nav-link" href="{% url 'story6:index' %}">Story 6</a>
                        <a class="dropdown-item nav-link" href="{% url 'story7:index' %}">Story 7</a>
                      </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
    {% block content %}
    
    {% endblock content %}


<!-- Footer -->

    <footer class="page-footer font-small">
      <!-- Copyright -->
      <div class="footer-copyright text-center py-3" style="font-style: bold; font-family: Poppins; color: white;">© 2020 :
        <a>Widyanto</a>
      </div>
      <!-- Copyright -->

    </footer>
    <!-- Footer -->


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    
    {% block js %}

    {% endblock js %}
  
</body>
</html>

templates/detailkuliah.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/kuliah.css' %}">
{% endblock css %}


{% block title %}Kuliah: {{kuliah.nama}}{% endblock title %}

{% block content %}
    <div class="container" style="margin-top: 10vh;">
        <h2 style="color: #f5ae16;">Detail Mata Kuliah</h2>
    </div>

    <div class="container" style="margin-top: 10vh;">
        <h6> Mata Kuliah :</h6>
        <p style="margin-left: 2rem;">{{ kuliah.nama }}</p>
        <h6> Dosen Pengajar : </h6>
        <p style="margin-left: 2rem;">{{ kuliah.dosen }}</p>
        <h6> Deskripsi : </h6>
        <p style="margin-left: 2rem;">{{ kuliah.desc }}</p>
        <h6> Semester : </h6>
        <p style="margin-left: 2rem;">{{ kuliah.semester }}</p>
        <h6> Jumlah SKS : </h6>
        <p style="margin-left: 2rem;">{{ kuliah.jml_sks }}</p>
    </div>

    <div class="container" style="margin-bottom: 2rem;">
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModalCenter">
    Hapus
    </button>
    <a type="button" class="btn btn-primary" href="../">Kembali</a>
    </div>

    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Hapus Kuliah {{kuliah.nama}}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Yakin ingin menghapus Kuliah {{kuliah.nama}}?</p>
        </div>
        <div class="modal-footer">
          <a type="button" class="btn btn-danger" href="{% url 'story5:delete_kuliah' kuliah.id %}">Delete</a>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>


  

{% endblock content %}

{% block js %}
{# <script src="{% static 'js/gallery.js'%}"></script> #}
    
{% endblock js %}

templates/editor.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	{{ form.media }}
</head>
<body>
	<!-- Include stylesheet -->
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

<!-- Create the editor container -->
<div id="editor">
  <p>Hello World!</p>
  <p>Some initial <strong>bold</strong> text</p>
  <p><br></p>
</div>

<div class="container">
	{{form}}
</div>

<!-- Include the Quill library -->
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

<!-- Initialize Quill editor -->
<script>
  var quill = new Quill('#editor', {
    theme: 'snow'
  });
</script>
</body>
</html>

templates/gallery.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/gallery.css' %}">
{% endblock css %}


{% block title %}Widyanto's Gallery{% endblock title %}

{% block content %}

<!-- Header -->
<header class="bg-primary text-center py-5 mb-4">
  <div class="container">
    <h1 class="font-weight-light text-white">Lets know me More!!</h1>
  </div>
</header>

<!-- Page Content -->
<div class="container-fluid">
  <div class="row">
    <!-- Team Member 1 -->
    <div class="col-xl-4 col-md-6 mb-4">
      <div class="card border-0 shadow">
        <img src="{% static 'img/foto3.jpg' %}" class="card-img-top" alt="..." >
        <div class="card-body text-center">
          <h5 class="card-title mb-0">Highschoolmate!!</h5>
          <div class="card-text text-black-50">My Friends and I when we met again at end of 2019</div>
        </div>
      </div>
    </div>
    <!-- Team Member 2 -->
    <div class="col-xl-4 col-md-6 mb-4">
      <div class="card border-0 shadow">
        <img src="{% static 'img/toki.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body text-center">
          <h5 class="card-title mb-0">TOKI Camp 2020</h5>
          <div class="card-text text-black-50">It was a superb event and I met superb people</div>
        </div>
      </div>
    </div>
    <!-- Team Member 3 -->
    <div class="col-xl-4 col-md-6 mb-4">
      <div class="card border-0 shadow">
        <img src="{% static 'img/pg.png' %}" class="card-img-top" alt="...">
        <div class="card-body text-center">
          <h5 class="card-title mb-0">Playground Event</h5>
          <div class="card-text text-black-50">Work with fun people in very serious division</div>
        </div>
      </div>
    </div>
    <!-- Team Member 4 -->
  </div>
  <!-- /.row -->
  <div class="row">
    <!-- Team Member 1 -->
    <div class="col-xl-4 col-md-6 mb-4">
      <div class="card border-0 shadow">
        <img src="{% static 'img/akpem.png' %}" class="card-img-top" alt="..." >
        <div class="card-body text-center">
          <h5 class="card-title mb-0">Academic and Leadership Department</h5>
          <div class="card-text text-black-50">I've ment the best people to work with</div>
        </div>
      </div>
    </div>
    <!-- Team Member 2 -->
    <div class="col-xl-4 col-md-6 mb-4">
      <div class="card border-0 shadow">
        <img src="{% static 'img/kintan.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body text-center">
          <h5 class="card-title mb-0">KUDETA go to Kintan</h5>
          <div class="card-text text-black-50">Kirung's Birthday was amazing</div>
        </div>
      </div>
    </div>
    <div class="col-xl-4 col-md-6 mb-4">
      <div class="card border-0 shadow">
        <img src="{% static 'img/fieldtrip.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body text-center">
          <h5 class="card-title mb-0">Fieldtrip Jogja</h5>
          <div class="card-text text-black-50">Was a very fun and unstressfull</div>
        </div>
      </div>
    </div>
 </div>
</div>
<!-- /.container -->

{% endblock content %}

{% block js %}
<script src="{% static 'js/gallery.js'%}"></script>
    
{% endblock js %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<!-- <link rel="stylesheet" href="{% static 'css/index.css' %}"> -->
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock css %}


{% block title %}Widyanto's Profile{% endblock title %}

{% block content %}
<!-- <button onclick="topFunction()" id="myBtn" title="Go to top">^</button> -->
	<div class="jumbotron jumbotron-fluid blue">
	  <div class="container">
	    <h4 class="name display-4">Widyanto Hadi<br>Nugroho</h4>
	    <div class="d-flex justify-content-start">
		  	<a class='icon social fb' href="//github.com/galacticor" target="_blank"><i class='fa fa-github'></i></a>
			  <a class='icon social in' href="//www.linkedin.com/in/widyantohd" target="_blank"><i class='fa fa-linkedin'></i></a>
			  <a class='icon social ig' href="//www.instagram.com/widyantonugroho" target="_blank"><i class='fa fa-instagram'></i></a>
			  <a class='icon social in' href="//api.whatsapp.com/send?phone=628226138789" target="_blank"><i class='fa fa-whatsapp'></i></a>
			</div>
	  </div>
	</div>
	<span id="aboutme"></span>
<div class="container yellow" >
  <!-- Content here -->
  <div class="row" style="margin-bottom: 6rem; margin-top: 10vh;">
  	<div class="col-lg-6 col-md-6" >
  		
  		<p style="margin-top: 2rem;">Hi, I am <span style="font-size: 2rem; color: #fe6600;">Widyanto.</span></p> 
  		<p>I’m currently pursuing Bachelor’s degree of Computer Science. </p>
  		<p style="margin-top: 6vh;">I was a Competitive Programmer and have enthusiasm at Data Science and Machine Learning. </p>
    </div>
  <!-- <div class="col-lg-6"></div> -->
    <div class="col-lg-6 col-md-6">
	   <div class="text-center">
	   	<img class="foto1 img-fluid" src="{% static 'img/foto1.png' %}" alt="#"></img>
	   </div>
    </div>
   </div>
</div>

<div class="container-fluid" id="profile">
	<div class="container">
        <h2 class="text-center" style="margin-top: 4rem; color: #03254c;"> Education</h2>
  </div>
  <!-- Content here -->
  			<div class="row" style="justify-content: center;">
                <div class="col-lg-3 col-md-6"> 
                    <div class="container" style="margin-top: 2rem;">
                        <div class="card">
                          <img class="card-img-top" src="{% static 'img/sma.jpg' %}" alt="Card image" style="width:100%;">
                          <div class="card-body">
                            <h4 class="card-title text-center">Senior High School</h4>
                            <p class="card-text text-center">SMAN Unggulan MH Thamrin</p>
                            <p class="card-text text-center">2016 - 2019</p>
                          </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6"> 
                    <div class="container" style="margin-top: 2rem;">
                        <div class="card">
                          <img class="card-img-top" src="{% static 'img/uai.jpg' %}" alt="Card image" style="width:100%;">
                          <div class="card-body">
                            <h4 class="card-title text-center">Universitas Indonesia</h4>
                            <p class="card-text text-center">Computer Science</p>
                            <p class="card-text text-center">2019 - present</p>
                          </div>
                        </div>
                    </div>
                </div>     
            </div>
        </div>
</div>

<div class="container">
	<div class="container">
     <h2 class="text-center" style="margin-top: 4rem; color: #03254c;"> Interest</h2>
  </div>
  <div class="row" style="margin-bottom: 6rem; margin-top: 6vh;">
  	<div class="col-lg-6 col-md-8" style="margin-bottom: 2rem;">
  		<p style="margin-top: 2rem;"> I have <span style="font-size: 2rem; color: #fe6600;">hobbies and interests</span></p> 
  		<p>I really like F1 a lot and have enthusiasm in Machine Learning. </p>
  		<p>I enjoy playing AWS DeepRacer to learn and stick with my hobby.</p>
    </div>
    <div class="col-lg-6 col-md-6">
	   <div class="text-center">
	   	<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
			  <ol class="carousel-indicators">
			    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
			    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
			  </ol>
			  <div class="carousel-inner">
			    <div class="carousel-item active">
			      <img src="{% static 'img/f1.png' %}" class="d-block w-100" alt="...">
			    </div>
			    <div class="carousel-item">
			      <img src="{% static 'img/deepracer.png' %}" class="d-block w-100" alt="...">
			    </div>
			  </div>
			  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
			    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
			    <span class="sr-only">Previous</span>
			  </a>
			  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
			    <span class="carousel-control-next-icon" aria-hidden="true"></span>
			    <span class="sr-only">Next</span>
			  </a>
			</div>
	   	<!-- <img class="foto1 img-fluid" src="{% static 'img/f1.png' %}" alt="#"></img> -->
	   </div>
    </div>
   </div>
</div>

<div class="container">
	<div class="container">
     <h2 class="text-center" style="margin-top: 4rem; color: #03254c;"> Experiences</h2>
  </div>
  <div class="row" style="margin-top: 6rem;">
  	<div class="col-lg-6 col-md-8" >
  		<p>Staff of Academic and Leadership Departmen </p>
  		<p>BEM Fasilkom UI</p>
  		<p>2020</p>
    </div>
	</div>
</div>

<div class="container">
  <div class="row" style="margin-bottom: 6rem; margin-top: 10vh;">
  	<div class="align-self-center col-lg-6 col-md-8" >
  		<h1 style="font-size: 8rem; font-style: bold; font-family: Josefin Sans">SKILL</h1>
    </div>
    <div class="col-lg-6 col-md-4">
     <h3>Python</h3>
	   <div class="progress">
			  <div class="progress-bar bg-success" role="progressbar" style="width: 90%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">9/10</div>
			</div>
		 <h3>Data Structure</h3>
			<div class="progress">
			  <div class="progress-bar bg-info" role="progressbar" style="width: 80%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">8/10</div>
			</div>
		 <h3>Java</h3>
			<div class="progress">
			  <div class="progress-bar bg-warning" role="progressbar" style="width: 85%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">8.5/10</div>
			</div>
		 <h3>Aptitude</h3>
			<div class="progress">
			  <div class="progress-bar bg-danger" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">10/10</div>
			</div>
	    </div>
   </div>
</div>

{% endblock content %}

{% block js %}
    <script src="{% static 'scroll-up.js' %}"></script>
{% endblock js %}

templates/matakuliah.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/kuliah.css' %}">

{% endblock css %}


{% block title %}Kuliah{% endblock title %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h2 class="display-4 text-center" style="margin-top: 30vh;">Daftar Mata Kuliah</h2>
    </div>
  </div>
<div class="container" style="min-height: 78vh;">
  <div class="container" style="margin-bottom: 10vh; margin-top: 10vh;">
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
    Tambah Kuliah
  </button>
  </div>
  <div class="table-responsive container" style="margin-top: 3rem;">
          <table class="table table-bordered table-hover">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th class="text-center">Mata Kuliah</th>
                  <th class="text-center">Nama Dosen</th>
                  <th class="text-center">Semester</th>
                  <th class="text-center">Action</th>
                </tr>
              </thead>
              {% for k in kuliah %}
              <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ k.nama }}</td>
                  <td>{{ k.dosen }}</td>
                  <td>{{ k.semester }}</td>
                  <td class="text-center"><a type="button" class="btn btn-info" href="{% url 'story5:detail_kuliah' k.id %}">Detail</a></td>
              </tr>
              {% endfor %}
          </table>
  </div>
  

  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Tambah Kuliah</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form method="post">
              {% csrf_token %}
              <div class="form-row">
                <div class="form-group col-md-6">
                  {{ form.nama|as_crispy_field }}
                </div>
                <div class="form-group col-md-6">
                  {{ form.dosen|as_crispy_field }}
                </div>
              </div>
              <div class="form-row">
                <div class="form-group col-md-6 mb-0">
                  {{ form.jml_sks|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0">
                  {{ form.semester|as_crispy_field }}
                </div>
                
              </div>
              {{ form.desc|as_crispy_field }}
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <!-- <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div> -->
      </div>
    </div>
  </div>
</div>


  

{% endblock content %}

{% block js %}
{% if cek %}
<script>
    $(document).ready(function(){
        $("#exampleModalCenter").modal('show');
    });
</script>
{% endif %}
    
{% endblock js %}

templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/story9.css' %}">
{% endblock css %}


{% block title %}Register{% endblock title %}

{% block content %}

{% endblock content %}

{% block js %}
<script src="{% static 'js/story9.js'%}"></script>
<script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>

{% endblock js %}

templates/story1.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    
{% endblock css %}


{% block title %}Widyanto's Profile{% endblock title %}

{% block content %}

	<div class="jumbotron jumbotron-fluid">
	  <div class="container">
	  	<h5 class="display-7 text-center">myprofile</h5> <br><br><br>
	    <h2 class="display-4 text-center">Widyanto Hadi N</h2>
	  </div>
	</div>

<div class="container" id="profile">
  <!-- Content here -->
  <div class="row" style="margin-top: 6rem;">
  	<div class="col-md-6 mx-auto">
  		<h4 style="margin-top: 2rem;">Widyanto Hadi Nugroho</h4>
  		<div class="row">
  			<table>
  				<tbody>
  					<tr>
  						<th><h5>Fakultas </h5></th>
  						<td><h5>: Ilmu Komputer</h5></td>
  					</tr>
  					<tr>
  						<th><h5>Jurusan </h5></th>
  						<th><h5>: Ilmu Komputer</h5></th>
  					</tr>
  					<tr>
  						<th><h5>Asal SMA </h5></th>
  						<th><h5>: SMAN MH Thamrin</h5></th>
  					</tr>
  					<tr>
  						<th><h5>Universitas</h5></th>
  						<th><h5>: Universitas Indonesia</h5></th>
  					</tr>
  				</tbody>
  			</table>
  		</div>
   </div>
  <div class="col-lg-6">
	   <div class="container">
	   	<img class="img-fluid" src="{% static 'img/foto3.jpg' %}" alt="#" style="margin-top: 2rem;"></img>
	   </div>
	 </div>
 </div>

 <div class="container">
 	<div class="text-center">Test</div>
 </div>



	  <!-- Button to Open the Modal -->
	<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
	  Gallery
	</button>

	<!-- The Modal -->
	<div class="modal" id="myModal">
	  <div class="modal-dialog">
	    <div class="modal-content">

	      <!-- Modal Header -->
	      <div class="modal-header">
	        <h4 class="modal-title">Foto - foto Gann</h4>
	        <button type="button" class="close" data-dismiss="modal">&times;</button>
	      </div>

	      <!-- Modal body -->
	      <div class="modal-body">
	        tar deh ye masukinnya
	      </div>

	      <!-- Modal footer -->
	      <div class="modal-footer">
	        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
	      </div>

	    </div>
	  </div>
	</div>
</div>

{% endblock content %}

{% block js %}
    
{% endblock js %}